language: php

sudo: true

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

services:
  - sqlite

before_script:
  - travis_retry composer self-update
  - composer require "illuminate/support:5.8"
  - composer show laravel/framework
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit --no-coverage